<?php $params = $this->getRequest()->getParams() ?>
<div class="edit-static-form">
	
	<div class="line">
		<div class="col-des-12 builder-title">
			<h2><?= __('Select Block') ?></h2>
		</div>
	</div>

	<div class="line">
		<div class="col-des-12 no-padding-right">
			<div class="bs-glyphicons">
				<div class="block-group">
					<h3><?= __('Static Content') ?></h3>
					<ul class="bs-glyphicons-list">
						<li id="heading-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'heading']) ?>')">
							<span class="glyphicon glyphicon-font"></span>
							<span class="glyphicon-class"><?= __('Heading') ?></span>
						</li>
						<li id="static-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'static']) ?>')">
							<span class="glyphicon glyphicon-text-width"></span>
							<span class="glyphicon-class"><?= __('Text content & Images') ?></span>
						</li>
						
						<li id="image" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'image']) ?>')">
							<span class="glyphicon glyphicon-picture"></span>
							<span class="glyphicon-class"><?= __('Images') ?></span>
						</li>
						
						<li id="owl-banner-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'owl_banner']) ?>')">
							<span class="glyphicon glyphicon-picture"></span>
							<span class="glyphicon-class"><?= __('OWL Carousel Slider') ?></span>
						</li>
						
						<li id="masonry-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'masonry']) ?>')">
							<span class="glyphicon glyphicon-picture"></span>
							<span class="glyphicon-class"><?= __('Masonry Gallery') ?></span>
						</li>

						<li id="banner-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'promo_banner']) ?>')">
							<span class="glyphicon glyphicon-gift"></span>
							<span class="glyphicon-class"><?= __('Promo Banner') ?></span>
						</li>
						
						<li id="profile-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'profile']) ?>')">
							<span class="glyphicon glyphicon-user"></span>
							<span class="glyphicon-class"><?= __('Profile') ?></span>
						</li>
						
						<li id="accordion-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'accordion']) ?>')">
							<span class="glyphicon glyphicon-align-justify"></span>
							<span class="glyphicon-class"><?= __('Accordion') ?></span>
						</li>
						
						<li id="video-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'video']) ?>')">
							<span class="fa fa-youtube-play" style="font-size:30px; margin:5px 0"></span>
							<span class="glyphicon-class"><?= __('Video') ?></span>
						</li>
						
						<li id="map-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'map']) ?>')">
							<span class="glyphicon glyphicon-map-marker"></span>
							<span class="glyphicon-class"><?= __('Google Map') ?></span>
						</li>
						
						<li id="box-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'content_box']) ?>')">
							<span class="glyphicon glyphicon-ok-sign"></span>
							<span class="glyphicon-class"><?= __('Content Box') ?></span>
						</li>
						
						<li id="counter-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'counter_box']) ?>')">
							<span class="glyphicon glyphicon-arrow-up"></span>
							<span class="glyphicon-class"><?= __('Counter Box') ?></span>
						</li>
						
						<li id="counter-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'countdown_box']) ?>')">
							<span class="glyphicon glyphicon-arrow-down"></span>
							<span class="glyphicon-class"><?= __('Countdown Box') ?></span>
						</li>
						
						<li id="chart-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'chart']) ?>')">
							<span class="fa fa-bar-chart" style="margin:5px 0 10px; font-size:25px"></span>
							<span class="glyphicon-class"><?= __('Chart') ?></span>
						</li>
						
						<li id="progress-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'progress_bar']) ?>')">
							<span class="glyphicon glyphicon-tasks"></span>
							<span class="glyphicon-class"><?= __('Progress Bar') ?></span>
						</li>
						
						<li id="circle-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'progress_circle']) ?>')">
							<span class="fa fa-circle-o-notch" style="margin:5px 0 10px; font-size:23px"></span>
							<span class="glyphicon-class"><?= __('Progress Circle') ?></span>
						</li>
						
						<li id="divider-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'divider']) ?>')">
							<span class="fa fa-ellipsis-h" style="margin:5px 0 10px; font-size:23px"></span>
							<span class="glyphicon-class"><?= __('Divider') ?></span>
						</li>
						
						<li id="list-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'list']) ?>')">
							<span class="glyphicon glyphicon-th-list"></span>
							<span class="glyphicon-class"><?= __('List') ?></span>
						</li>
						
						<li id="button-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'button']) ?>')">
							<span class="glyphicon glyphicon-link"></span>
							<span class="glyphicon-class"><?= __('Button') ?></span>
						</li>
						
						<li id="table-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'table']) ?>')">
							<span class="glyphicon glyphicon-th"></span>
							<span class="glyphicon-class"><?= __('Table') ?></span>
						</li>
						
						<li id="static-tabs-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'static_tabs']) ?>')">
							<span class="fa fa-object-ungroup"></span>
							<span class="glyphicon-class"><?= __('Tabs') ?></span>
						</li>
						
						<li id="modal-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'modal_popup']) ?>')">
							<span class="fa fa-window-maximize" style="font-size:22px; margin-bottom:8px"></span>
							<span class="glyphicon-class"><?= __('Modal Popup') ?></span>
						</li>
						
						<li id="form-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'form']) ?>')">
							<span class="fa fa-object-group"></span>
							<span class="glyphicon-class"><?= __('Form') ?></span>
						</li>
					</ul>
				</div>
				
				<div class="block-group">
					<h3><?= __('Catalog') ?></h3>
					<ul class="bs-glyphicons-list" id="list-item">
						<li id="snapppt-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'category_list']) ?>')">
							<span class="glyphicon glyphicon-list-alt"></span>
							<span class="glyphicon-class"><?= __('Category List') ?></span>
						</li>
						
						<li id="category-product" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'category_products']) ?>')">
							<span class="glyphicon glyphicon-align-center"></span>
							<span class="glyphicon-class"><?= __('Category Products') ?></span>
						</li>

						<li id="new-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'new_products']) ?>')">
							<span class="glyphicon glyphicon-fire"></span>
							<span class="glyphicon-class"><?= __('New Products') ?></span>
						</li>
						
						<li id="attribute-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'attribute_products']) ?>')">
							<span class="glyphicon glyphicon-flag"></span>
							<span class="glyphicon-class"><?= __('Products by Attribute') ?></span>
						</li>
						
						<li id="sale-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'sale']) ?>')">
							<span class="glyphicon glyphicon-certificate"></span>
							<span class="glyphicon-class"><?= __('Sale Products') ?></span>
						</li>
						
						<li id="rate-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'rate']) ?>')">
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon-class"><?= __('Top Rate Products') ?></span>
						</li>
						
						
						
						<li id="deals-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'deals']) ?>')">
							<span class="glyphicon glyphicon-tag"></span>
							<span class="glyphicon-class"><?= __('Deals') ?></span>
						</li>
						
						<li id="special_deal" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'special_deal']) ?>')">
							<span class="glyphicon glyphicon-tag"></span>
							<span class="glyphicon-class"><?= __('Special Deal') ?></span>
						</li>
						
						<li id="tabs-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'tabs']) ?>')">
							<span class="fa fa-object-ungroup"></span>
							<span class="glyphicon-class"><?= __('Product Tabs') ?></span>
						</li>
						
						<li id="special_product" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'special_product']) ?>')">
							<span class="glyphicon glyphicon-qrcode"></span>
							<span class="glyphicon-class"><?= __('Single Product') ?></span>
						</li>
						

					</ul>
				</div>
			
				<div class="block-group">
					<h3><?= __('Social') ?></h3>
					<ul class="bs-glyphicons-list">
						<li id="facebook-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'facebook']) ?>')">
							<span class="fa fa-facebook-square" style="font-size:30px"></span>
							<span class="glyphicon-class"><?= __('Facebook Fanbox') ?></span>
						</li>
						
						<li id="twitter-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'twitter']) ?>')">
							<span class="fa fa-twitter-square" style="font-size:30px"></span>
							<span class="glyphicon-class"><?= __('Twitter Timeline') ?></span>
						</li>
						
						<li id="instagram-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'instagram']) ?>')">
							<span class="glyphicon glyphicon-camera" style="font-size:30px"></span>
							<span class="glyphicon-class"><?= __('Instagram') ?></span>
						</li>
						<li id="snapppt-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'instagram_shop']) ?>')">
							<span class="fa fa-instagram" style="font-size:30px"></span>
							<span class="glyphicon-class"><?= __('Instagram Shop') ?></span>
						</li>
					</ul>
				</div>
			
				<?php if($this->isModuleActive('MGS_Lookbook') || $this->isModuleActive('MGS_Blog') || $this->isModuleActive('MGS_Portfolio') || $this->isModuleActive('MGS_Testimonial')): ?>
					<div class="block-group">
						<h3><?= __('Extensions') ?></h3>
						<ul class="bs-glyphicons-list">
							<?php if($this->isModuleActive('MGS_Lookbook')): ?>
								<li id="lookbook-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'lookbook']) ?>')">
									<span class="glyphicon glyphicon-remove-circle" style="transform: rotate(45deg); -webkit-transform: rotate(45deg); -ms-transform: rotate(45deg);"></span>
									<span class="glyphicon-class"><?= __('Lookbook') ?></span>
								</li>
								
								<li id="lookbook-slider-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'lookbook_slider']) ?>')">
									<span class="glyphicon glyphicon-picture"></span>
									<span class="glyphicon-class"><?= __('Lookbook Slider') ?></span>
								</li>
							<?php endif ?>
							
							<?php if($this->isModuleActive('MGS_Blog')): ?>
								<li id="blog-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'latest_post']) ?>')">
									<span class="glyphicon glyphicon-comment"></span>
									<span class="glyphicon-class"><?= __('Latest Post') ?></span>
								</li>
							<?php endif ?>
							
							<?php if($this->isModuleActive('MGS_Portfolio')): ?>
								<li id="blog-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'portfolio']) ?>')">
									<span class="glyphicon glyphicon-folder-open"></span>
									<span class="glyphicon-class"><?= __('Portfolio') ?></span>
								</li>
							<?php endif ?>
							
							<?php if($this->isModuleActive('MGS_Testimonial')): ?>
								<li id="blog-item" onclick="setLocation('<?= $this->getUrl('fbuilder/create/element', ['page_id'=>$this->getRequest()->getParam('page_id'), 'block'=>$params['name'], 'type'=>'testimonial']) ?>')">
									<span class="fa fa-quote-left"></span>&nbsp;&nbsp;<span class="fa fa-quote-right"></span>
									<span class="glyphicon-class"><?= __('Testimonial') ?></span>
								</li>
							<?php endif ?>
						</ul>
					</div>
				<?php endif ?>
			</div>
		</div>
	</div>
</div>