<?php 
	use Magento\Framework\App\Action\Action;
	
	$viewMode = 'grid';
	$image = 'category_page_grid';
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	$_product = $this->getLoadProduct($this->getProductId());
	$_productNameStripped = $block->stripTags($_product->getName(), null, true);
	$productImage = $block->getImage($_product, $image);
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
	$builderHelper = $this->helper('MGS\Fbuilder\Helper\Data');
	$hideName = $this->getBlockData('hide_name');
	$hideReview = $this->getBlockData('hide_review');
	$hidePrice = $this->getBlockData('hide_price');
	$hideAddCart = $this->getBlockData('hide_addcart');
	$hideAddWishlist = $this->getBlockData('hide_addwishlist');
	$hideAddCompare = $this->getBlockData('hide_addcompare');
	$hideTime = $this->getBlockData('hide_time');
	$hideDiscount = $this->getBlockData('hide_discount');
	$hideSavedPrice = $this->getBlockData('hide_saved_price');
	
	$price = $_product->getOrigData('price');
	$finalPrice = $_product->getFinalPrice();
	$savedPrice = $price - $finalPrice;
	
	$htmlStructure = $builderHelper->getStoreConfig('fbuilder/html_structure/deal_product_list');
?>

<?php 
	
	// add to cart

	$aHelper = $this->Helper('MGS\AjaxCart\Helper\Data');
	$animationType = $aHelper->getConfig('ajaxcart/additional/animation_type');
	$animationType;

	$_animationTypeShowCart = false;
	if($animationType == 'showcart') {
		$_animationTypeShowCart = true;
	}

	$typeId = $_product->getTypeId();

	//echo $typeId;
	$redirectByTypeId = false;

	if($typeId == 'simple' || $typeId == 'virtual') {
		$redirectByTypeId = true;
	}

	$linkDetailProduct = $_product->getProductUrl();

?>

<div class="product-item-info" data-container="product-list">
	<div class="product-top">
		<div class="product-image">
			<a href="<?php  echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
				<?php echo $productImage->toHtml() ?>
			</a>
			<?php if($hideDiscount!=1): ?>
			<?php 
				if(($finalPrice<$price)){
					$percent = round(($savedPrice * 100) / $price);
					echo '<span class="product-ribbon sale-ribbon"><span>-'.$percent.'%</span></span>';
				}
			?>
			<?php endif ?>
		</div>
		
		<?php // Product Detail ?>
		<div class="product details product-item-details">
			<?php if($hideName!=1): ?>
				<strong class="product name product-item-name">
					<a class="product-item-link"
					   href="<?php echo $_product->getProductUrl() ?>">
						<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
					</a>
				</strong>
			<?php endif ?>
			
			<?php if($hideReview!=1): ?>
				<?php echo $block->getReviewsSummaryHtml($_product, $templateType, true) ?>
			<?php endif ?>
			
			<?php if($hidePrice!=1): ?>
				<?php echo $block->getProductPrice($_product) ?>
			<?php endif ?>
			
			<?php if($hideSavedPrice!=1): ?>
				<?php 
					$savedText = '<span class="saved-price">'.$builderHelper->decodeHtmlTag($this->getBlockData('fbuilder_saved_text')).' %1'.'</span>';
					$formattedPrice = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($savedPrice, true, true);
					echo __($savedText, $formattedPrice);
				?>
			<?php endif ?>
			
			<?php if($hideTime!=1): ?>
				<?php echo $this->getLayout()->createBlock('MGS\Fbuilder\Block\Products\Deals')->setProduct($_product)->setTemplate('MGS_Fbuilder::products/deals/time.phtml')->setBlockData($this->getBlockData())->toHtml() ?>
			<?php endif ?>
			
			
			<?php if(($hideAddCart!=1) || ($hideAddWishlist!=1) ||($hideAddCompare!=1)): ?>
				<div class="product-item-inner">
					<div class="product actions product-item-actions">
						<?php if($hideAddCart!=1): ?>
							<div class="actions-primary">
								<?php if ($_product->isSaleable()): ?>
									<?php $postParams = $block->getAddToCartPostParams($_product); ?>
									<form data-role="tocart-form" data-product-sku="<?=  /* @NoEscape */ $_product->getSku() ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
										<input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
										<input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
										<?= $block->getBlockHtml('formkey') ?>
										<?php if($_animationTypeShowCart == true && $redirectByTypeId == false){ ?>
											<button type="submit" title="<?= $block->escapeHtml(__('Add to Cart')) ?>" class="action tocart primary" onClick='window.location="<?php echo $linkDetailProduct; ?>"'>
												<span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
											</button>
										<?php }else{?>
											<button type="submit" title="<?= $block->escapeHtml(__('Add to Cart')) ?>" class="action tocart primary">
												<span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
											</button>
										<?php } ?>
									</form>
								<?php else: ?>
									<?php if ($_product->isAvailable()): ?>
										<div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
									<?php else: ?>
										<div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
									<?php endif; ?>
								<?php endif; ?>
							</div>
						<?php endif ?>
						
						<?php if(($hideAddWishlist!=1) ||($hideAddCompare!=1)): ?>
							<div data-role="add-to-links" class="actions-secondary">
								<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && ($hideAddWishlist!=1)): ?>
									<a href="#" class="action towishlist" title="<?= __('Add to Wish List') ?>" aria-label="<?= __('Add to Wish List') ?>" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($block->getProduct()) ?>' data-action="add-to-wishlist" role="button">
										<span><?= __('Add to Wish List') ?></span>
									</a>
								<?php endif; ?>
								<?php if($hideAddCompare!=1): ?>
									<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
									<a href="#" class="action tocompare" title="<?= $block->escapeHtml(__('Add to Compare')) ?>" aria-label="<?= $block->escapeHtml(__('Add to Compare')) ?>" data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataParams($_product) ?>' role="button">
										<span><?= /* @escapeNotVerified */ __('Add to Compare') ?></span>
									</a>
								<?php endif ?>
							</div>
						<?php endif ?>
					</div>
				</div>
			<?php endif ?>
		</div>
	</div>
</div>