<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

?>
<div class="contact-form">
	<form class="form contact"
		  action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
		  id="contact-form"
		  method="post"
		  data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
		  data-mage-init='{"validation":{}}'>
		<div class="fieldset">
			<div class="field name required">
				<label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Name') ?></span></label>
				<div class="control">
					<input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
				</div>
			</div>
			<div class="field email required">
				<label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
				<div class="control">
					<input name="email" id="contact-email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
				</div>
			</div>
			<div class="field comment required">
				<label class="label" for="comment"><span><?php /* @escapeNotVerified */ echo __('Your message') ?></span></label>
				<div class="control">
					<textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
				</div>
			</div>
			<?= $block->getChildHtml('form.additional.info'); ?>
			<label class="label note" for="note"><span><?php /* @escapeNotVerified */ echo __('All fields marked * are required') ?>
		</div>
		<div class="actions-toolbar">
			<div class="primary">
				<input type="hidden" name="hideit" id="hideit" value="" />
				<button type="submit" title="<?php /* @escapeNotVerified */ echo __('Send Message') ?>" class="action submit primary">
					<span><?php /* @escapeNotVerified */ echo __('Send Message') ?></span>
				</button>
			</div>
		</div>
	</form>
	<div class="contact-information">
		<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact_us_information_block')->toHtml(); ?>
	</div>
</div>
<div class="contact-store">
	<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact_store_block')->toHtml(); ?>
</div>
