<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \MGS\InstantSearch\Block\SearchResult\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$limit = $block->getPositionLimit();
$themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config');
$perRowDefault = $themeSettingConfig->getStoreConfig('instantsearch/general/per_row');
$perRowTablet = $themeSettingConfig->getStoreConfig('instantsearch/general/per_row_tablet');
$perRowMobile = $themeSettingConfig->getStoreConfig('instantsearch/general/per_row_mobile');
?>
<div class="products-result">
<div class="block block-title">
    <h4><?= __('Products') ?></h4>
</div>
<?php if (!$_productCollection->count()): ?>
    <div class="wrapper message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
	<?php
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = $block->showShortDescription();
        $showReview = $block->showReview();
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        /**
         * Position for actions regarding image size changing in vde if needed
         */
        $pos = $block->getPositioned();
    ?>
	<div class="products active-slider wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
		<?php $iterator = 1; ?>
		<ol class="line products items product-items row-<?=$perRowDefault; ?> row-tablet-<?=$perRowTablet; ?> row-mobile-<?=$perRowMobile; ?>">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            	<?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product product-item col">' : '</li><li class="product product-item col">' ?>
            	<div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getProductImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
					<div class="product-top">
						<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
							<?= $productImage->toHtml(); ?>
						</a>
						<div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?= $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                    <?php endif; ?>
								</div>
                            </div>
                        </div>
					</div>
            		<div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
						<div class="product-name">
							<strong class="product name product-item-name">
								<a class="product-item-link"
								   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
									<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
								</a>
							</strong>
						</div>
                        <?= $showReview ? $block->getReviewsSummaryHtml($_product, $templateType) : ''; ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
					
                       
                    </div>
            	</div>
            	<?=($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
		 <?php if($_productCollection->count() && $_productCollection->getSize() > $limit): ?>
			<div class="view-more border-radius">
				<a class="action secondary" href="<?php /* @escapeNotVerified */ echo $block->getResultUrl() ?>"><?php /* @escapeNotVerified */ echo $block->getViewMoreLabel() ?></a>
			</div>
		<?php endif; ?>
	</div>

    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
</div>