<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div data-bind="scope: 'messages'">
	<div data-bind="visible: isVisible(), click: RemoveMessage">
		<div role="alert" data-bind="foreach: { data: cookieMessages, as: 'message' }" class="messages">
			<div data-bind="attr: {
				class: 'bounceInRight animated message-' + message.type + ' ' + message.type + ' message',
				'data-ui-id': 'message-' + message.type
			}">
				<div class="text" data-bind="html: message.text"></div>
				<div class="close" style="display: none;" data-bind="visible: true"></div>
			</div>
		</div>
		<div role="alert" data-bind="foreach: { data: messages().messages, as: 'message' }" class="messages">
			<div data-bind="attr: {
				class: 'bounceInRight animated message-' + message.type + ' ' + message.type + ' message',
				'data-ui-id': 'message-' + message.type
			}">
				<div class="text" data-bind="html: message.text"></div>
				<div class="close" style="display: none;" data-bind="visible: true"></div>
			</div>
		</div>
	</div>
</div> 
<script type="text/x-magento-init">
  {
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                    "messages": {
                        "component": "Magento_Theme/js/view/messages"
                    }
                }
            }
        }
  }
</script>