<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

?>

<div class="contact">
	<div class="form-info">
		<div class="contact-form">
			<span class="control-form switch-info">+</span>
			<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact_form')->toHtml(); ?>
			<div class="form">
				<form class="form contact"
					  action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
					  id="contact-form"
					  method="post"
					  data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
					  data-mage-init='{"validation":{}}'>
					<div class="fieldset">
						<div class="field name required">
							<div class="control">
								<input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}" placeholder="Name"/>
							</div>
						</div>
						<div class="field email required">
							<div class="control">
								<input name="email" id="contact-email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}" placeholder="Email Address"/>
							</div>
						</div>
						<div class="field comment required">
							<div class="control">
								<textarea placeholder="Message" name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
							</div>
						</div>
						<?= $block->getChildHtml('form.additional.info'); ?>
					</div>
					<div class="actions-toolbar">
						<div class="primary">
							<input type="hidden" name="hideit" id="hideit" value="" />
							<button type="submit" title="<?php /* @escapeNotVerified */ echo __('Send Message') ?>" class="action submit primary">
								<span><?php /* @escapeNotVerified */ echo __('Send Message') ?></span>
							</button>
						</div>
					</div>
				</form>
				<div class="contact-information">
					<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact_us_information_block')->toHtml(); ?>
				</div>
			</div>
		</div>

		<div class="contact-info">
			<span class="control-form switch-form">-</span>
			<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact_info')->toHtml(); ?>
		</div>
	</div>

	<div class="contact-store">
		<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact_store_block')->toHtml(); ?>
	</div>
	<div class="map-google">
		<?php echo $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('MGS_ThemeSettings::html/google_map.phtml')->toHtml() ?>
	</div>

	</div>
</div>
