<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div class="mgs-instant-search-dropdown" data-bind="scope: 'instant_search_form'">
	<!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
    }
}
</script>
<script>
    window.instantSearch = <?php /* @escapeNotVerified */ echo $block->getInstantSearchConfig();?>;
</script>