<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Address $block */
?>
<div class="block block-dashboard-addresses">
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */ echo __('Address Book') ?></strong>
    </div>
    <div class="block-content">
        <div class="box box-billing-address">
            <strong class="box-title">
                <span><?php /* @escapeNotVerified */ echo __('Default Billing Address') ?></span>
            </strong>
            <div class="box-content">
                <address>
                    <?= $block->getPrimaryBillingAddressHtml() ?>
                </address>
            </div>
            <div class="box-actions">
                <a class="action edit edit-billding" href="<?php /* @escapeNotVerified */ echo $block->getPrimaryBillingAddressEditUrl() ?>" data-ui-id="default-billing-edit-link"><span><?php /* @escapeNotVerified */ echo __('Edit your billing address') ?></span></a>
            </div>
        </div>
        <div class="box box-shipping-address">
            <strong class="box-title">
                <span><?php /* @escapeNotVerified */ echo __('Default Shipping Address') ?></span>
            </strong>
            <div class="box-content">
                <address>
                    <?= $block->getPrimaryShippingAddressHtml() ?>
                </address>
            </div>
            <div class="box-actions">
                <a class="action edit edit-billding" href="<?php /* @escapeNotVerified */ echo $block->getPrimaryShippingAddressEditUrl() ?>" data-ui-id="default-shipping-edit-link"><span><?php /* @escapeNotVerified */ echo __('Edit your billing address') ?></span></a>
            </div>
        </div>
    </div>
	<?php /*<a class="action edit address-book" href="<?php  echo $block->getAddressBookUrl() ?>"><span><?php  echo __('Manage Addresses') ?></span></a>*/ ?>
</div>
